import React from 'react'
import { View, Text, Button, StyleSheet, ScrollView } from "react-native";
import { F1_Container, F1_TituloPagina, F1_TituloMeioPagina, F1_Titulo, F1_Texto, F1_Rodape } from './styles';

export default function PoliticaPrivacidade() {
    return (
        <F1_Container>
            <F1_TituloPagina style={{fontFamily: 'Ubuntu-Medium', marginTop: 10}}>Política de Privacidade GF1</F1_TituloPagina>
            <F1_Texto style={{fontFamily: 'OpenSans-Regular'}}>Artemis Tech construiu o aplicativo Guia da F1 como um aplicativo gratuito. Este SERVIÇO é fornecido pela Artemis Tech sem nenhum custo e deve ser usado como esta.
                {"\n"}{"\n"}Esta página é usada para informar os visitantes sobre nossas políticas de coleta, uso e divulgação de informações pessoais, caso alguém decida usar nosso serviço.
                {"\n"}{"\n"}Se você optar por usar nosso Serviço, concorda com a coleta e o uso de informações relacionadas a esta política. As informações pessoais que coletamos são usadas para fornecer e melhorar o serviço. Não usaremos ou compartilharemos suas informações com ninguém, exceto conforme descrito nesta Política de Privacidade.
                {"\n"}{"\n"}Os termos utilizados nesta Política de Privacidade têm os mesmos significados que em nossos Termos e Condições, que estão acessíveis no Guia da F1, salvo disposição em contrário nesta Política de Privacidade.</F1_Texto>
            <F1_Titulo style={{fontFamily: 'Ubuntu-Medium', marginTop: -10}}>Coleta e uso de informações</F1_Titulo>
            <F1_Texto style={{fontFamily: 'OpenSans-Regular'}}>Para uma melhor experiência, ao usar nosso Serviço, podemos exigir que você nos forneça algumas informações de identificação pessoal. As informações que solicitamos serão mantidas em seu dispositivo e não serão coletadas por nós de forma alguma.
                {"\n"}{"\n"}O aplicativo usa serviços de terceiros que podem coletar informações usadas para identificá-lo.
                {"\n"}{"\n"}Queremos informar que sempre que você usa nosso Serviço, em caso de erro no aplicativo, coletamos dados e informações (através de produtos de terceiros) em seu telefone chamado Log Data. Esses dados de registro podem incluir informações como endereço de protocolo de Internet ("IP") do dispositivo, nome do dispositivo, versão do sistema operacional, configuração do aplicativo ao utilizar meu serviço, hora e data de uso do serviço e outras estatísticas.</F1_Texto>
            <F1_Titulo style={{fontFamily: 'Ubuntu-Medium'}}>Cookies</F1_Titulo>
            <F1_Texto style={{fontFamily: 'OpenSans-Regular'}}>Cookies são arquivos com uma pequena quantidade de dados que são comumente usados como identificadores únicos anônimos. Estes são enviados para o seu navegador a partir dos sites que você visita e são armazenados na memória interna do seu dispositivo.
                {"\n"}{"\n"}Este Serviço não usa esses “cookies” explicitamente. No entanto, o aplicativo pode usar código e bibliotecas de terceiros que usam “cookies” para coletar informações e melhorar seus serviços.</F1_Texto>
            <F1_Titulo style={{fontFamily: 'Ubuntu-Medium'}}>Provedores de serviço</F1_Titulo>
            <F1_Texto style={{fontFamily: 'OpenSans-Regular'}}>Podemos empregar empresas e indivíduos terceirizados devido aos seguintes motivos:
                {"\n"}{"\n"}&nbsp; - Para facilitar nosso Serviço;{"\n"}
                &nbsp; - Para fornecer o Serviço em nosso nome;{"\n"}
                &nbsp; - Para realizar serviços relacionados ao Serviço; ou{"\n"}
                &nbsp; - Para nos ajudar a analisar como nosso Serviço é usado.{"\n"}
                Queremos informar aos usuários deste Serviço que esses terceiros têm acesso às suas Informações Pessoais. O motivo é realizar as tarefas atribuídas a eles em nosso nome. No entanto, eles são obrigados a não divulgar ou usar as informações para qualquer outra finalidade.</F1_Texto>
            <F1_Titulo style={{fontFamily: 'Ubuntu-Medium'}}>Segurança</F1_Titulo>
            <F1_Texto style={{fontFamily: 'OpenSans-Regular'}}>Valorizamos sua confiança em nos fornecer suas informações pessoais, portanto, estamos nos esforçando para usar meios comercialmente aceitáveis de protegê-las. Mas lembre-se que nenhum método de transmissão pela internet, ou método de armazenamento eletrônico é 100% seguro e confiável, e não posso garantir sua segurança absoluta.</F1_Texto>
            <F1_Titulo style={{fontFamily: 'Ubuntu-Medium'}}>Links para outros sites</F1_Titulo>
            <F1_Texto style={{fontFamily: 'OpenSans-Regular'}}>Este Serviço pode conter links para outros sites. Se você clicar em um link de terceiros, será direcionado para esse site. Observe que esses sites externos não são operados por nós. Portanto, aconselho fortemente que você revise a Política de Privacidade desses sites. Não temos controle e não assumimos nenhuma responsabilidade pelo conteúdo, políticas de privacidade ou práticas de sites ou serviços de terceiros.</F1_Texto>
            <F1_Titulo>Mudanças nesta Política de Privacidade</F1_Titulo>
            <F1_Texto style={{fontFamily: 'OpenSans-Regular'}}>Podemos atualizar nossa Política de Privacidade de tempos em tempos. Assim, você é aconselhado a revisar esta página periodicamente para quaisquer alterações. Iremos notificá-lo sobre quaisquer alterações publicando a nova Política de Privacidade nesta página.{"\n"}{"\n"}Esta política é efetiva a partir de 06/08/2023</F1_Texto>
            <F1_TituloMeioPagina style={{fontFamily: 'Ubuntu-Medium'}}>Termos e Condições</F1_TituloMeioPagina>
            <F1_Texto style={{fontFamily: 'OpenSans-Regular'}}>Ao baixar ou usar o aplicativo, esses termos serão aplicados automaticamente a você – portanto, certifique-se de lê-los cuidadosamente antes de usar o aplicativo. Você não tem permissão para copiar ou modificar o aplicativo, qualquer parte do aplicativo ou nossas marcas registradas de forma alguma. Você não tem permissão para tentar extrair o código-fonte do aplicativo e também não deve tentar traduzir o aplicativo para outros idiomas ou criar versões derivadas. O aplicativo em si e todas as marcas registradas, direitos autorais, direitos de banco de dados e outros direitos de propriedade intelectual relacionados a ele ainda pertencem à Artemis Tech.{"\n"}{"\n"}A Artemis Tech está empenhada em garantir que o aplicativo seja o mais útil e eficiente possível. Por esse motivo, nos reservamos o direito de fazer alterações no aplicativo ou cobrar por seus serviços, a qualquer momento e por qualquer motivo. Nunca cobraremos pelo aplicativo ou seus serviços sem deixar bem claro para você exatamente o que você está pagando.{"\n"}{"\n"}A aplicação Guia da F1 armazena e trata os dados pessoais que nos forneceu, para a prestação do meu Serviço. É sua responsabilidade manter seu telefone e acesso ao aplicativo seguros. Portanto, recomendamos que você não faça jailbreak ou root em seu telefone, que é o processo de remoção de restrições e limitações de software impostas pelo sistema operacional oficial do seu dispositivo. Isso pode tornar seu telefone vulnerável a malware/vírus/programas maliciosos, comprometer os recursos de segurança do seu telefone e pode significar que o aplicativo Guia da F1 não funcionará corretamente ou não funcionará.{"\n"}{"\n"}O aplicativo usa serviços de terceiros que declaram seus Termos e Condições.{"\n"}{"\n"}Você deve estar ciente de que há certas coisas pelas quais a Artemis Tech não se responsabiliza. Certas funções do aplicativo exigirão que o aplicativo tenha uma conexão ativa com a Internet. A conexão pode ser Wi-Fi ou fornecida pelo seu provedor de rede móvel, mas a Artemis Tech não pode se responsabilizar pelo aplicativo não funcionar com todas as funcionalidades se você não tiver acesso ao Wi-Fi e não tiver nenhum dos seus permissão de dados restante.{"\n"}{"\n"}
            Se você estiver usando o aplicativo fora de uma área com Wi-Fi, lembre-se de que os termos do contrato com sua operadora de rede móvel ainda serão aplicados. Como resultado, você pode ser cobrado por sua operadora de celular pelo custo dos dados durante a conexão durante o acesso ao aplicativo ou outras cobranças de terceiros. Ao usar o aplicativo, você aceita a responsabilidade por tais cobranças, incluindo cobranças de dados de roaming se você usar o aplicativo fora de seu território de origem (ou seja, região ou país) sem desativar o roaming de dados. Se você não for o pagador da conta do dispositivo no qual está usando o aplicativo, saiba que presumimos que você recebeu permissão do pagador para usar o aplicativo.{"\n"}{"\n"}Na mesma linha, a Artemis Tech nem sempre pode se responsabilizar pela maneira como você usa o aplicativo, ou seja, você precisa garantir que seu dispositivo permaneça carregado - se ficar sem bateria e você não conseguir ligá-lo para aproveitar o Serviço, Artemis A tecnologia não pode aceitar a responsabilidade.{"\n"}{"\n"}No que diz respeito à responsabilidade da Artemis Tech pelo uso do aplicativo, quando você estiver usando o aplicativo, é importante ter em mente que, embora nos esforcemos para garantir que ele esteja sempre atualizado e correto, contamos com terceiros para forneça informações para que possamos disponibilizá-las a você. A Artemis Tech não se responsabiliza por qualquer perda, direta ou indireta, que você sofra como resultado de confiar totalmente nesta funcionalidade do aplicativo.
            {"\n"}{"\n"}Em algum momento, podemos desejar atualizar o aplicativo. O aplicativo está atualmente disponível no Android - os requisitos para o sistema (e para quaisquer sistemas adicionais para os quais decidimos estender a disponibilidade do aplicativo) podem mudar e você precisará baixar as atualizações se quiser continuar usando o aplicativo . A Artemis Tech não promete que sempre atualizará o aplicativo para que seja relevante para você e/ou funcione com a versão do Android que você instalou em seu dispositivo. No entanto, você promete sempre aceitar as atualizações do aplicativo quando oferecidas a você. Também podemos interromper o fornecimento do aplicativo e encerrar o uso dele a qualquer momento, sem avisar você. A menos que digamos o contrário, após qualquer rescisão, (a) os direitos e licenças concedidos a você nestes termos terminarão; (b) você deve parar de usar o aplicativo e (se necessário) excluí-lo do seu dispositivo.</F1_Texto>
            <F1_Titulo style={{fontFamily: 'Ubuntu-Medium', marginTop: -20}}>Alterações nestes Termos e Condições</F1_Titulo>
            <F1_Texto style={{fontFamily: 'OpenSans-Regular'}}>Podemos atualizar nossos Termos e Condições de tempos em tempos. Assim, você é aconselhado a revisar esta página periodicamente para quaisquer alterações. Iremos notificá-lo sobre quaisquer alterações publicando os novos Termos e Condições nesta página.{"\n"}{"\n"}Estes termos e condições são efetivos a partir de 08/06/2023</F1_Texto>
            <F1_Titulo style={{fontFamily: 'Ubuntu-Medium'}}>Contate-nos</F1_Titulo>
            <F1_Texto style={{fontFamily: 'OpenSans-Regular', marginBottom: 35}}>Se você tiver alguma dúvida ou sugestão sobre nossa Política de Privacidade, não hesite em nos contatar pelo e-mail <Text style={{fontFamily: 'OpenSans-Bold'}}>guiadaF1@gmail.com</Text>.</F1_Texto>
            <F1_Rodape style={{fontFamily: 'OpenSans-Regular'}}>Esta página de política de privacidade foi criada em privacypolicytemplate.net e modificada/gerada pelo App Privacy Policy Generator</F1_Rodape>
        </F1_Container>
    )
}